name: promptify-dj-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.25.2
  - python-dotenv
  - pysoundfile
  - ffmpeg
  - librosa
  - pip
  - pip:
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - streamlit==1.28.1
      - streamlit-webrtc==0.47.1
      - av==10.0.0
      - python-multipart==0.0.6
      - openai==1.3.7
      - spotipy==2.23.0
      - git+https://github.com/openai/whisper.git
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - httpx==0.25.2
      - requests==2.31.0
      - pydantic==2.5.0
      - loguru==0.7.2
